### ISSUE TITLE
Testing Error

### ISSUE THREAD

**Issue by RankJay** [zeeem/EndPresso#1]
Hello there,

I was keen to look and understand your project `EndPresso`. But there is this error that is not allowing me to run the model. Traceback Tree has been attached here. Can you please help me as to how can I resolve it?

```
E:\EndPresso-master>python detect.py --images images/test5.jpg --quality 10
Loading network.....
Traceback (most recent call last):
  File "E:\EndPresso-master\detect.py", line 122, in <module>
    model.load_weights(args.weightsfile)
  File "E:\EndPresso-master\darknet.py", line 436, in load_weights
    bn_biases = bn_biases.view_as(bn.bias.data)
RuntimeError: shape '[32]' is invalid for input of size 28
```

**Comment by zeeem** [comment]
Hi there, it seems like a PyTorch or darknet version issue. 
Sorry, I don't have the environment setup for this project anymore, So I won't be able to test the issue on my end.

**Comment by RankJay** [comment]
Hey there,
No problem, I have found out a solution to it, line 122 in detect.py where you declare the

https://github.com/zeeem/EndPresso/blob/1a2fd58f205c1de14176c7cfdec22f1be3667e31/detect.py#L122

Just commenting on the line will do the work.
